PREFIX roevo: <http://purl.org/wf4ever/roevo#>
PREFIX ro: <http://purl.org/wf4ever/ro#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT
{
	<%s> rdfs:label ?liveid ;
		a ?liveclass .
	?middle roevo:isSnapshotOf <%<s>;
		roevo:hasPreviousVersion ?father ;
		rdfs:label ?id ;
		a ?class .
	?son roevo:isSnapshotOf <%<s>;
		roevo:isArchiveOf <%<s>;
		roevo:hasPreviousVersion ?middle ;
		rdfs:label ?sonid ;
		a ?sonclass .
	?grandson ?grandsonrelation <%<s>;
		roevo:hasPreviousVersion ?son ;
		rdfs:label ?grandsonid ;
		a ?grandsonclass .
	?father roevo:isSnapshotOf <%<s>;
		roevo:isArchiveOf <%<s>;
		roevo:hasPreviousVersion ?grandfather ;
		rdfs:label ?fatherid ;
		a ?fatherclass .
	?grandfather roevo:isSnapshotOf <%<s>;
		roevo:isArchiveOf <%<s>;
		rdfs:label ?grandfatherid ;
		a ?grandfatherclass .
	<%<s>roevo:derivedFrom ?source .
	?source rdfs:label ?sourceid ;
		a ?sourceclass .
}
WHERE
{
	OPTIONAL { <%<s> rdfs:label ?liveid . }
	OPTIONAL { <%<s> a ?liveclass . }
	
	OPTIONAL
	{
		{ ?grandson roevo:isSnapshotOf <%<s> . }
		UNION
		{ ?grandson roevo:isArchiveOf <%<s> . }
		?grandson ?grandsonrelation <%<s> .
		FILTER NOT EXISTS { ?grandgrandson roevo:hasPreviousVersion ?grandson . }
		OPTIONAL { ?grandson rdfs:label ?grandsonid . }
		OPTIONAL { ?grandson a ?grandsonclass . }

		OPTIONAL
		{
			?grandson roevo:hasPreviousVersion ?son .
			OPTIONAL { ?son rdfs:label ?sonid . }
			OPTIONAL { ?son roevo:isSnapshotOf <%<s>. }
			OPTIONAL { ?son roevo:isArchiveOf <%<s>. }
			OPTIONAL { ?son a ?sonclass . }

			OPTIONAL 
			{ 
				?son roevo:hasPreviousVersion ?middle .
				OPTIONAL { ?middle rdfs:label ?id . }
				OPTIONAL { ?middle roevo:isSnapshotOf <%<s>. }
				OPTIONAL { ?middle roevo:isArchiveOf <%<s>. }
				OPTIONAL { ?middle a ?class . }

				OPTIONAL
				{
					?middle roevo:hasPreviousVersion ?father .
					OPTIONAL { ?father rdfs:label ?fatherid . }
					OPTIONAL { ?father roevo:isSnapshotOf <%<s>. }
					OPTIONAL { ?father roevo:isArchiveOf <%<s>. }
					OPTIONAL { ?father a ?fatherclass . }

					OPTIONAL
					{
						?father roevo:hasPreviousVersion ?grandfather .
						OPTIONAL { ?grandfather rdfs:label ?grandfatherid . }
						OPTIONAL { ?grandfather roevo:isSnapshotOf <%<s>. }
						OPTIONAL { ?grandfather roevo:isArchiveOf <%<s>. }
						OPTIONAL { ?grandfather a ?grandfatherclass . }
					}
				}
			}
		}
	}
	
	OPTIONAL
	{
		<%<s>roevo:derivedFrom ?source .
		OPTIONAL { ?source rdfs:label ?sourceid . }
		OPTIONAL { ?source a ?sourceclass . }
	}
}
