PREFIX roevo: <http://purl.org/wf4ever/roevo#>
PREFIX ro: <http://purl.org/wf4ever/ro#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>

CONSTRUCT
{
	<%s> roevo:isSnapshotOf ?live ;
		prov:wasRevisionOf ?father ;
		rdfs:label ?id ;
		a ?class .
	?live rdfs:label ?liveid ;
		a ?liveclass .
	?son roevo:isSnapshotOf ?live ;
		prov:wasRevisionOf <%<s> ;
		rdfs:label ?sonid ;
		a ?sonclass .
	?grandson roevo:isSnapshotOf ?live ;
		prov:wasRevisionOf ?son ;
		rdfs:label ?grandsonid ;
		a ?grandsonclass .
	?father roevo:isSnapshotOf ?live ;
		prov:wasRevisionOf ?grandfather ;
		rdfs:label ?fatherid ;
		a ?fatherclass .
	?grandfather roevo:isSnapshotOf ?live ;
		rdfs:label ?grandfatherid ;
		a ?grandfatherclass .
	?fork roevo:derivedFrom <%<s> ;
		rdfs:label ?forkid ;
		a ?forkclass .
}
WHERE
{
	OPTIONAL 
	{ 
		<%<s> roevo:isSnapshotOf ?live . 
		OPTIONAL { ?live rdfs:label ?liveid . }
		OPTIONAL { ?live a ?liveclass . }
	}
	
	OPTIONAL { <%<s> rdfs:label ?id . }
	OPTIONAL { <%<s> a ?class . }

	OPTIONAL
	{
		<%<s> prov:wasRevisionOf ?father .
		OPTIONAL { ?father rdfs:label ?fatherid . }
		OPTIONAL { ?father roevo:isSnapshotOf ?live . }
		OPTIONAL { ?father a ?fatherclass . }
		OPTIONAL{
			?father prov:wasRevisionOf ?grandfather .
			OPTIONAL { ?grandfather rdfs:label ?grandfatherid . }
			OPTIONAL { ?grandfather roevo:isSnapshotOf ?live . }
			OPTIONAL { ?grandfather a ?grandfatherclass . }
		}
	}

	OPTIONAL
	{
		?son prov:wasRevisionOf <%<s> .
		OPTIONAL { ?son rdfs:label ?sonid . }
		OPTIONAL { ?son roevo:isSnapshotOf ?live . }
		OPTIONAL { ?son a ?sonclass . }
		OPTIONAL
		{
			?grandson prov:wasRevisionOf ?son ;
			OPTIONAL { ?grandson rdfs:label ?grandsonid . }
			OPTIONAL { ?grandson roevo:isSnapshotOf ?live . }
			OPTIONAL { ?grandson a ?grandsonclass . }
		}
	}

	OPTIONAL
	{
		?fork roevo:derivedFrom <%<s> .
		OPTIONAL { ?fork rdfs:label ?forkid . }
		OPTIONAL { ?fork a ?forkclass . }
	}
}
