PREFIX roevo: <http://purl.org/wf4ever/roevo#>
PREFIX ro: <http://purl.org/wf4ever/ro#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT
{
	<%s> roevo:isSnapshotOf ?live ;
		roevo:hasPreviousVersion ?father ;
		rdfs:label ?id ;
		a ?class .
	?live rdfs:label ?liveid ;
		a ?liveclass .
	?son roevo:isSnapshotOf ?live ;
		roevo:hasPreviousVersion <%<s> ;
		rdfs:label ?sonid ;
		a ?sonclass .
	?grandson roevo:isSnapshotOf ?live ;
		roevo:hasPreviousVersion ?son ;
		rdfs:label ?grandsonid ;
		a ?grandsonclass .
	?father roevo:isSnapshotOf ?live ;
		roevo:hasPreviousVersion ?grandfather ;
		rdfs:label ?fatherid ;
		a ?fatherclass .
	?grandfather roevo:isSnapshotOf ?live ;
		rdfs:label ?grandfatherid ;
		a ?grandfatherclass .
	?derived roevo:derivedFrom <%<s> ;
		rdfs:label ?derivedid ;
		a ?derivedclass .
}
WHERE
{
	OPTIONAL 
	{ 
		<%<s> roevo:isSnapshotOf ?live . 
		OPTIONAL { ?live rdfs:label ?liveid . }
		OPTIONAL { ?live a ?liveclass . }
	}
	
	OPTIONAL { <%<s> rdfs:label ?id . }
	OPTIONAL { <%<s> a ?class . }

	OPTIONAL
	{
		<%<s> roevo:hasPreviousVersion ?father .
		OPTIONAL { ?father rdfs:label ?fatherid . }
		OPTIONAL { ?father roevo:isSnapshotOf ?live . }
		OPTIONAL { ?father a ?fatherclass . }
		OPTIONAL{
			?father roevo:hasPreviousVersion ?grandfather .
			OPTIONAL { ?grandfather rdfs:label ?grandfatherid . }
			OPTIONAL { ?grandfather roevo:isSnapshotOf ?live . }
			OPTIONAL { ?grandfather a ?grandfatherclass . }
		}
	}

	OPTIONAL
	{
		?son roevo:hasPreviousVersion <%<s> .
		OPTIONAL { ?son rdfs:label ?sonid . }
		OPTIONAL { ?son roevo:isSnapshotOf ?live . }
		OPTIONAL { ?son a ?sonclass . }
		OPTIONAL
		{
			?grandson roevo:hasPreviousVersion ?son ;
			OPTIONAL { ?grandson rdfs:label ?grandsonid . }
			OPTIONAL { ?grandson roevo:isSnapshotOf ?live . }
			OPTIONAL { ?grandson a ?grandsonclass . }
		}
	}

	OPTIONAL
	{
		?derived roevo:derivedFrom <%<s> .
		OPTIONAL { ?derived rdfs:label ?derivedid . }
		OPTIONAL { ?derived roevo:isSnapshotOf ?live . }
		OPTIONAL { ?derived a ?derivedclass . }
	}
}
