PREFIX wfprov: <http://purl.org/wf4ever/wfprov#>

SELECT ?workflow ?run ?resource 
WHERE { 
<%s> <http://www.openarchives.org/ore/terms/aggregates> ?workflow .
?run wfprov:describedByWorkflow ?workflow ;
wfprov:usedInput ?resource .
}